### PR TITLE
include Jon in the readme

### PR DESCRIPTION
**Pull request by SethTisue**
hi @propensive

### CODE REVIEW

**Comment by SethTisue** [comment]
review/merge by @MasseGuillaume ?

**Comment by SethTisue** [comment]
and/or if you want me to give me merge rights here I wouldn't complain :-)

**Comment by heathermiller** [comment]
I'm sorry that no one responded to you, Seth. It's a pity that everyone really seems to be letting this Scala Spree totally slip... I'm not happy about it. I'll add you.

**Comment by propensive** [comment]
Thanks! Only just saw this this morning...

**Pull request merged**
